name: mood_music
description: A mood-based music player using ML Kit
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_text_recognition: ^0.11.0
  sentiment_dart: ^0.0.5
  image_picker: ^1.0.7
  audioplayers: ^6.0.0
  google_fonts: ^6.3.2

  just_audio: ^0.9.37
  audio_session: ^0.1.16
  http: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/music/happy.mp3
    - assets/music/sad.mp3
    - assets/music/neutral.mp3
    - assets/images/emoji.jpg
